# Generated by Django 2.2.1 on 2019-06-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Item name')),
                ('item_num', models.IntegerField(verbose_name='No. of units')),
                ('date_stored', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of entry')),
                ('date_removed', models.DateTimeField(null=True)),
                ('fragile', models.BooleanField(verbose_name='Fragile')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('units', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('t', 'Tonnes')], max_length=20, verbose_name='Units')),
                ('item_class', models.CharField(choices=[('A', 'Electronics'), ('B', 'Chemicals'), ('C', 'Books'), ('D', 'Clothing'), ('E', 'Food'), ('F', 'Other')], default='A', max_length=1, verbose_name='Item class')),
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Item ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
